# Generated by Django 3.2.3 on 2021-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
